creditswarm/urls.py
# Copyright (c) 2012 Jason McVetta.

from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin

from case.views import home_view
from case.views import LoginView
#
from case.views import CaseCreateView
from case.views import CaseDetailView
from case.views import CaseUpdateView
from case.views import CaseDeleteView
from case.views import CaseConfirmationView
#
from case.views import AccountCreateView
from case.views import AccountUpdateView
from case.views import AccountDeleteView
#
from case.views import InquiryCreateView
from case.views import InquiryUpdateView
from case.views import InquiryDeleteView
#
from case.views import DemographicCreateView
from case.views import DemographicUpdateView
from case.views import DemographicDeleteView
#
from case.views import cra_login
from case.views import CraCaseDetailView
from case.views import CraLoginView
#
from profile.views import UserProfileView


admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'pijyn.views.home', name='home'),
    # url(r'^pijyn/', include('pijyn.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('social_auth.urls')),
    url(r'^$', home_view, name='home'),
    url(r'^login/$', LoginView.as_view(), name="login"),
    url(r'^logout/$', 
        'django.contrib.auth.views.logout', 
        { 'next_page': '/' },
        name='logout',
        ),
    #
    # Social Auth
    #
    url(r'', include('social_auth.urls')),
    #
    # Account management
    #
    url(r'^profile/edit$', 
        UserProfileView.as_view(),
        name='profile-edit',
        ),
    #
    # Case
    #
    url(r'^case/new/$', CaseCreateView.as_view(), name='case-new'),
    url(r'^case/(?P<pk>\d+)/$', CaseDetailView.as_view(), name='case-detail'),
    url(r'^case/(?P<pk>\d+)/edit/$', CaseUpdateView.as_view(), name='case-edit'),
    url(r'^case/(?P<pk>\d+)/delete/$', CaseDeleteView.as_view(), name='case-delete'),
    url(r'^case/(?P<pk>\d+)/submit/$', CaseConfirmationView.as_view(), name='case-confirm'),
    #
    # Account
    #
    url(r'^case/(?P<case_pk>\d+)/account/new/$', AccountCreateView.as_view(), name='account-new'),
    url(r'^case/account/(?P<pk>\d+)/edit/$', AccountUpdateView.as_view(), name='account-edit'),
    url(r'^case/account/(?P<pk>\d+)/delete/$', AccountDeleteView.as_view(), name='account-delete'),
    #
    # Inquiry
    #
    url(r'^case/(?P<case_pk>\d+)/inquiry/new/$', InquiryCreateView.as_view(), name='inquiry-new'),
    url(r'^case/inquiry/(?P<pk>\d+)/edit/$', InquiryUpdateView.as_view(), name='inquiry-edit'),
    url(r'^case/inquiry/(?P<pk>\d+)/delete/$', InquiryDeleteView.as_view(), name='inquiry-delete'),
    #
    # Demographic
    #
    url(r'^case/(?P<case_pk>\d+)/demographic/new/$', DemographicCreateView.as_view(), name='demographic-new'),
    url(r'^case/demographic/(?P<pk>\d+)/edit/$', DemographicUpdateView.as_view(), name='demographic-edit'),
    url(r'^case/demographic/(?P<pk>\d+)/delete/$', DemographicDeleteView.as_view(), name='demographic-delete'),
    #
    # Credit Reporting Agency
    #
    url(r'^cra/login/$', cra_login, name='cra-login'),
    url(r'^cra/case/(?P<pk>\d+)/$', CraCaseDetailView.as_view(), name='cra-case-detail'),
)

urlpatterns += staticfiles_urlpatterns()

case/models.py
# Copyright (c) 2012 Jason McVetta.

import datetime
#
from django.db import models
from django.utils import timezone
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.contrib.sites.models import Site
#
from storages.backends.s3boto import S3BotoStorage
#
from templated_email import send_templated_mail
#
from creditswarm.settings import DEFAULT_FROM_EMAIL
from creditswarm.settings import CREDIT_REPORTING_AGENCIES as AGENCIES


STATUS_CHOICES = [
    ('D', 'Draft'),
    ('Q', 'Queued for Send'),
    ('S', 'Sent'),
    ]

CRA_CHOICES = [(key, AGENCIES[key]['name']) for key in AGENCIES]

DETAIL_REASON_CHOICES = [
    ('unknown_acct', 'Unknown Account'),
    ('not_mine', 'Not Mine'),
    ('on_time', 'Paid On Time'),
    ('fraud', 'Fraud / ID Theft'),
    ('unauthorized', 'Unauthorized Charge / Fee / Interest'),
    ('bankruptcy', 'Bankruptcy Discharge'),
    ('expired', 'Expired Account'),
    ('wrong_details', 'Wrong Account Details'),
    ('other', 'Other'),
    ]

BAD_INFO_TYPE_CHOICES = [
    ('name', 'Incorrect Name'),
    ('dob', 'Incorrect Date of Birth'),
    ('employer', 'Incorrect Employer'),
    ('address', 'Incorrect Address'),
    ('spouse', 'Incorrect Spouse'),
    ('phone', 'Incorrect Telephone'),
    ('other', 'Other Incorrect Information'),
    ]


class Case(models.Model):
    '''
    A Credit Swarm dispute case, containing one or more varieties of Dispute
    '''
    user = models.ForeignKey(User)
    ts_created = models.DateTimeField(auto_now_add=True,
        verbose_name='Created Timestamp')
    ts_updated = models.DateTimeField(auto_now=True,
        verbose_name='Updated Timestamp')
    ts_submitted = models.DateTimeField(blank=True, null=True)
    ts_transmitted = models.DateTimeField(blank=True, null=True)
    status = models.CharField(max_length=3, choices=STATUS_CHOICES, default='D')
    #
    # Credit Report
    #
    agency = models.CharField(max_length=128, choices=CRA_CHOICES, 
        verbose_name='Credit Reporting Agency')
    report_number = models.CharField(max_length=128)
    
    class Meta:
        ordering = ['-ts_updated']
        permissions = [
            ('cra_view', 'CRA can view case'),
            ]
    
    def get_absolute_url(self):
        return reverse('case-detail', kwargs={'pk': self.pk})
    
    def __str__(self):
        return '%s: %s %s (%s)' % (self.pk, self.get_agency_display(), self.report_number, self.user)
    
    def ready_to_submit(self):
        '''
        Returns True if this Dispute has enough information attached that it
        is ready to submit.
        '''
        return bool(
            self.account_set.all() 
            or self.inquiry_set.all()
            or self.demographic_set.all()
            )
    
    @property
    def case_number(self):
        '''
        An formatted number officially designating this case.
        '''
        s = u'%012d' % self.pk
        return s[:3] + '-' + s[3:6] + '-' + s[6:9] + '-' + s[9:]
    
    @property
    def case_id(self):
        '''
        An formatted string, consisting of the prefix NCDAC- and the case 
        number, officially designating this case.
        '''
        return 'NCDAC-' + self.case_number
    
    def email_cra(self):
        '''
        Sends a dispute email for to the Credit Reporting Agency
        '''
        send_templated_mail(
            template_name = 'cra_dispute_notification',
            from_email = DEFAULT_FROM_EMAIL,
            recipient_list = [AGENCIES[self.agency]['email'],],
            context = {
                'object': self,
                'current_site': Site.objects.get_current(),
                },
            # Optional:
            # cc=['cc@example.com'],
            # bcc=['bcc@example.com'],
            # headers={'My-Custom-Header':'Custom Value'},
            # template_ 
            template_suffix = 'html',
            )
        self.status = 'S'
        self.ts_transmitted = timezone.now()
        self.save()


class Dispute(models.Model):
    '''
    Abstract base class for the several varieties of credit dispute
    '''
    case = models.ForeignKey(Case) 
    ts_created = models.DateTimeField(auto_now_add=True,
        verbose_name='Created Timestamp')
    ts_updated = models.DateTimeField(auto_now=True,
        verbose_name='Updated Timestamp')

    class Meta:
        abstract = True



class Inquiry(Dispute):
    '''
    A disputed credit score inquiry
    '''
    company_name = models.CharField(max_length=128)
    date = models.DateField(default=datetime.date.today)
    
    class Meta:
        verbose_name = 'Credit Inquiry'
        verbose_name_plural = 'Credit Inquiries'
    

class Account(Dispute):
    '''
    A disputed account detail
    '''
    creditor = models.CharField(max_length=128, help_text='Name of creditor company')
    account_number = models.CharField(max_length=128)
    reason = models.CharField(max_length=32, choices=DETAIL_REASON_CHOICES, 
        help_text='Reason you are disputing this account')
    explanation = models.TextField(blank=True, null=True, 
        help_text='Explain why this account detail is incorrect.')
    evidence = models.FileField(null=True, blank=True,
        upload_to='evidence',
        help_text='Upload document supporting your dispute.',
        storage=S3BotoStorage(bucket='creditswarm-secure'),
        )
    
    class Meta:
        verbose_name = 'Account Detail'


class Demographic(Dispute):
    '''
    Disputed demographic info
    '''
    problem = models.CharField(max_length=32, blank=True, null=True, 
        choices=BAD_INFO_TYPE_CHOICES)
    explanation = models.TextField(blank=True, null=True)

case/forms.py
# Copyright (c) 2012 Jason McVetta.

from django import forms
from django.core.exceptions import ValidationError

from case.models import Case
from case.models import Account
from case.models import Inquiry
from case.models import Demographic


class CaseForm(forms.ModelForm):
    class Meta:
        model = Case
        exclude = ['user', 'status', 'ts_submitted', 'ts_transmitted']


class AccountForm(forms.ModelForm):
    class Meta:
        model = Account
        exclude = ['case']


class InquiryForm(forms.ModelForm):
    class Meta:
        model = Inquiry
        exclude = ['case']

class DemographicForm(forms.ModelForm):
    class Meta:
        model = Demographic
        exclude = ['case']

templates/case/account_confirm_delete.html
{% extends "base.html" %}
{% load url from future %}


{% block title %}{% block header %}
Are you sure you want to delete this account?
{% endblock %}{% endblock %}


{% block content %}

<ul>
	<li>
		Creditor Name: {{ object.creditor }}
	</li>
	<li>
		Account Number: {{ object.account_number }}
	</li>
	<li>
		Reason: {{ object.get_reason_display }}
	</li>
	<li>
		Explanation: {{ object.explanation }}
	</li>
</ul>

<form method="POST">
	{% csrf_token %}
	<button type="submit" class="btn btn-danger">
		<i class="icon-trash"></i> Yes, Delete It!
	</button>
	<a href="{% url "case-detail" object.case.pk %}" class="btn">
		Cancel
	</a>
</form>

{% endblock %}

templates/case/account_form.html
{% extends "base.html" %}
{% load url from future %}
{% load bootstrap %}

{% block extracss %} 
<link href="{{ STATIC_URL }}/css/datepicker.css" rel="stylesheet">
{% endblock %}


{% block extrascript %} 
<script src="{{ STATIC_URL }}js/bootstrap-datepicker.js"></script>
<script>
	$(function(){
		$('#id_inquiry_date').datepicker({
			format: 'yyyy-mm-dd'
		});
	})
</script>
{% endblock %}


{% block title %}{% block header %}
Disputed Account Detail
{% endblock %}{% endblock %}


{% block content %}

<form method="post" class="form-horizontal" enctype="multipart/form-data">
	{% csrf_token %}
	{{ form|bootstrap }}
	<input type="submit" class="btn btn-primary" value="Save" />
	{% if object %}
	<a href="{% url "case-detail" object.case.pk %}" class="btn">Cancel</a>
	<a href="{% url "account-delete" object.pk %}" class="btn btn-danger pull-right">
		<i class="icon-trash"></i> Delete
	</a>
	{% else %}
	<a href="javascript:history.go(-1)" class="btn">Cancel</a>
	{% endif %}
</form>

{% endblock %}

templates/case/case_confirm_delete.html
{% extends "base.html" %}
{% load url from future %}

{% block title %}{% block header %}
Are you sure you want to delete this Credit Report Dispute?
{% endblock %}{% endblock %}


{% block content %}

<ul>
	<li>
		Credit Swarm Dispute Number: {{ object.pk }}
	</li>
	<li>
		Credit Reporting Agency: {{ object.get_agency_display }}
	</li>
	<li>
		Credit Report Number: {{ object.report_number }}
	</li>
	<li>
		Status: 
		{{ object.get_status_display }}
	</li>
</ul>


<form method="POST">
	{% csrf_token %}
	<button type="submit" class="btn btn-danger">
		<i class="icon-trash"></i> Yes, Delete It!
	</button>
	<a href="{% url "case-detail" object.pk %}" class="btn">
		Cancel
	</a>
</form>
{% endblock %}

templates/case/case_confirmation.html
{% extends "base.html" %}
{% load url from future %}


{% block title %}{% block header %}
Confirm Dispute Details
{% endblock %}{% endblock %}


{% block content %}

<h2>
	Dispute: {{ object.get_agency_display }} credit report #{{ object.report_number }}
</h2>

{% include "case/case_detail_display.html" %}

<hr />

<p class="lead">
	Once your case has been submitted, you will <b>not</b> be able to edit 
	any of the information.
</p>
<form method="POST">
	<button type="submit" class="btn btn-warning">
		<i class="icon-ok"></i> Confirm and Submit Case
	</button>
	<a href="{% url "case-detail" object.pk %}" class="btn">Edit</a>
	{% csrf_token %}
</form>

{% endblock %}

templates/case/case_detail.html
{% extends "base.html" %}
{% load url from future %}


{% block title %}{% block header %}
Dispute: {{ object.get_agency_display }} credit report #{{ object.report_number }}
{% endblock %}{% endblock %}


{% block content %}

{% if object.status == "D" %}
	{% include "case/case_detail_edit.html" %}
{% else %}
	{% include "case/case_detail_display.html" %}
{% endif %}

{% endblock %}

templates/case/case_detail_display.html
{% load url from future %}

<!------------------------------------------------------------------------------
	
Credit Report

------------------------------------------------------------------------------->

<dl>
	<dt>
		Dispute Case ID
	</dt>
	<dd>
		{{ object.case_id }}
	</dd>
	{% if object.ts_transmitted %}
	<dt>
		Dispute Case Transmitted
	</dt>
	<dd>
		{{ object.ts_transmitted }}
	</dd>
	{% endif %}
	<dt>
		Credit Reporting Agency
	</dt>
	<dd>
		{{ object.get_agency_display }}
	</dd>
	<dt>
		Credit Report Number
	</dt>
	<dd>
		{{ object.report_number }}
	</dd>
	<dt>
		Consumer Given Name
	</dt>
	<dd>
		{{ object.user.get_profile.given_name }}
	</dd>
	<dt>
		Consumer Family Name
	</dt>
	<dd>
		{{ object.user.get_profile.family_name }}
	</dd>
	<dt>
		Consumer Address
	</dt>
	<dd>
		{{ object.user.get_profile.address1 }}
		{% if object.user.get_profile.address2 %}
		<br>{{ object.user.get_profile.address2 }}
		{% endif %}
		<br>{{ object.user.get_profile.city }}, 
		{{ object.user.get_profile.state }} 
		{{ object.user.get_profile.zip }}
	</dd>
	<dt>
		Consumer Date of Birth
	</dt>
	<dd>
		{{ object.user.get_profile.date_of_birth }}
	</dd>
	<dt>
		Consumer SSN
	</dt>
	<dd>
		{{ object.user.get_profile.ssn }}
	</dd>
</dl>

<!------------------------------------------------------------------------------
	
Account Details

------------------------------------------------------------------------------->

<hr />

<h2>
	Disputed Account Details
</h2>

{% if object.account_set.all %}

{% for account in object.account_set.all %}

<h3>
	{{ account.creditor }} #{{ account.account_number }} (Disputed Account Detail)
</h3>
<dl>
	<dt>
		Creditor
	</dt>
	<dd>
		{{ account.creditor }}
	</dd>
	<dt>
		Account Number
	</dt>
	<dd>
		{{ account.account_number }}
	</dd>
	<dt>
		Reason
	</dt>
	<dd>
		{{ account.get_reason_display }}
	</dd>
	<dt>
		Explanation
	</dt>
	<dd>
		{{ account.explanation|linebreaks|default:"-" }}
	</dd>
	<dt>
		Supporting Document
	</dt>
	<dd>
		{% if account.evidence %}
		<a href="{{ account.evidence.url }}">
			{{ account.evidence }}
		</a>
		{% else %}
		-
		{% endif %}
	</dd>
</dl>
{% if not forloop.last %}
<hr />
{% endif %}

{% endfor %}

{% else %}

<p>
	No disputed account details.
</p>

{% endif %}


<!------------------------------------------------------------------------------
	
Inquiries

------------------------------------------------------------------------------->

<hr />

<h2>
	Disputed Inquiries
</h2>

{% if object.inquiry_set.all %}

	{% for inquiry in object.inquiry_set.all %}
	<h3>
		{{ inquiry.company_name }} {{ inquiry.date|date:"d M Y" }} (Disputed Credit Inquiry)
	</h3>
	<dl>
		<dt>
			Company Name
		</dt>
		<dd>
			{{ inquiry.company_name }}
		</dd>
		<dt>
			Date of Inquiry
		</dt>
		<dd>
			{{ inquiry.date }}
		</dd>
	</dl>
	{% if not forloop.last %}
		<hr />
	{% endif %}
	{% endfor %}

{% else %}

	<p>
		No disputed inquiries.
	</p>

{% endif %}


<!------------------------------------------------------------------------------
	
Demographic Info

------------------------------------------------------------------------------->

<hr />

<h2>
	Incorrect Personal Information
</h2>

{% if object.demographic_set.all %}

	{% for dem in object.demographic_set.all %}
	<h3>
		{{ dem.get_problem_display|slice:"10:" }} (Incorrect Personal Information)
	</h3>
	<dl>
		<dt>
			Problem
		</dt>
		<dd>
			{{ dem.get_problem_display }}
		</dd>
		<dt>
			Explanation
		</dt>
		<dd>
			{{ dem.explanation|linebreaks }}
		</dd>
	</dl>
	{% if not forloop.last %}
		<hr />
	{% endif %}
	{% endfor %}

{% else %}

<p>
	No incorrect personal information.
</p>

{% endif %}

templates/case/case_detail_edit.html
{% load url from future %}

<!------------------------------------------------------------------------------
	
Credit Report

------------------------------------------------------------------------------->

<dl>
	<dt>
		Dispute Case ID
	</dt>
	<dd>
		{{ object.case_id }}
	</dd>
	<dt>
		Credit Reporting Agency
	</dt>
	<dd>
		{{ object.get_agency_display }}
	</dd>
	<dt>
		Credit Report Number
	</dt>
	<dd>
		{{ object.report_number }}
	</dd>
</dl>

<p>
	<a href="{% url "case-edit" object.pk %}" class="btn">
		Edit credit report number
	</a>
</p>


<!------------------------------------------------------------------------------
	
Account Details

------------------------------------------------------------------------------->

<hr />

<h2>
	Disputed Account Details
</h2>

{% if object.account_set.all %}

<table class="table table-striped" data-provides="rowlink">
	<thead>
		<tr>
			<th>
				Creditor
			</th>
			<th>
				Account Number
			</th>
			<th>
				Reason
			</th>
			<th>
				Explanation
			</th>
			<th>
				Evidence
			</th>
		</tr>
	</thead>
	<tbody>
	{% for account in object.account_set.all %}
		<tr>
			<td>
				<a href="{% url "account-edit" account.pk %}">
					{{ account.creditor }}
				</a>
			</td>
			<td>
				{{ account.account_number }}
			</td>
			<td>
				{{ account.get_reason_display }}
			</td>
			<td>
				{{ account.explanation|truncatechars:80 }}
			</td>
			<td>
				{% if account.evidence %}
				<a href="{{ account.evidence.url }}">
					{{ account.evidence.name }}
				</a>
				{% endif %}
			</td>
		</tr>
	{% endfor %}
	</tbody>
</table>

{% else %}
<p>
	<strong>No account details added.</strong>
</p>
{% endif %}

<p>
	<a href="{% url "account-new" object.pk %}" class="btn">
		Add new account detail...
	</a>
</p>


<!------------------------------------------------------------------------------
	
Inquiries

------------------------------------------------------------------------------->

<hr />

<h2>
	Disputed Inquiries
</h2>

{% if object.inquiry_set.all %}

<table class="table table-striped" data-provides="rowlink">
	<thead>
		<tr>
			<th>
				Company Name
			</th>
			<th>
				Inquiry Date
			</th>
		</tr>
	</thead>
	<tbody>
		{% for inquiry in object.inquiry_set.all %}
		<tr>
			<td>
				<a href="{% url "inquiry-edit" inquiry.pk %}">
					{{ inquiry.company_name }}
				</a>
			</td>
			<td>
				{{ inquiry.date }}
			</td>
		</tr>
		{% endfor %}
	</tbody>
</table>

{% else %}

<p>
	<strong>No inquiries added.</strong>
</p>

{% endif %}

<p>
	<a href="{% url "inquiry-new" object.pk %}" class="btn">
		Add new inquiry...
	</a>
</p>


<!------------------------------------------------------------------------------
	
Demographic Info

------------------------------------------------------------------------------->

<hr />

<h2>
	Incorrect Personal Information
</h2>

{% if object.demographic_set.all %}

<table class="table table-striped" data-provides="rowlink">
	<thead>
		<tr>
			<th>
				Problem
			</th>
			<th>
				Explanation
			</th>
		</tr>
	</thead>
	<tbody>
		{% for dem in object.demographic_set.all %}
		<tr>
			<td>
				<a href="{% url "demographic-edit" dem.pk %}">
					{{ dem.get_problem_display }}
				</a>
			</td>
			<td>
				{{ dem.explanation|truncatechars:80 }}
			</td>
		</tr>
		{% endfor %}
	</tbody>
</table>

{% else %}

<p>
	<strong>No personal information added.</strong>
</p>

{% endif %}

<p>
	<a href="{% url "demographic-new" object.pk %}" class="btn">
		Add new personal information...
	</a>
</p>


<!------------------------------------------------------------------------------

Preview and Confirm

------------------------------------------------------------------------------->

<hr />

{% if not object.ready_to_submit %}
<p>
	<i>You must add at least one cased account detail or inquiry before submitting your case.</i>
</p>
{% endif %}

<p>
	{% if object.ready_to_submit %}
	<a href="{% url "case-confirm" object.pk %}" class="btn btn-success">
	{% else %}
	<a href="#" class="btn btn-primary disabled">
	{% endif %}
		<i class="icon-ok"></i> Preview and Confirm
	</a>
	<a href="{% url "case-delete" object.pk %}" class="btn btn-danger pull-right">
		<i class="icon-trash"></i> Delete
	</a>
</p>

templates/case/case_form.html
{% extends "base.html" %}
{% load url from future %}
{% load bootstrap %}


{% block title %}{% block header %}
Credit Report Dispute
{% endblock %}{% endblock %}


{% block extracss %} 
<link href="{{ STATIC_URL }}/css/datepicker.css" rel="stylesheet">
{% endblock %}


{% block extrascript %} 
<script src="{{ STATIC_URL }}js/bootstrap-datepicker.js"></script>
<script>
	$(function(){
		$('#id_inquiry_date').datepicker({
			format: 'yyyy-mm-dd'
		});
	})
</script>
{% endblock %}


{% block content %}

<form method="post" class="form-horizontal">
	{% csrf_token %}
	{{ form|bootstrap }}
	<input type="submit" class="btn btn-primary" value="Save and Add Detail" />
	<a href="{% url "home" %}" class="btn">Cancel</a>
</form>

{% endblock %}

templates/case/demographic_confirm_delete.html
{% extends "base.html" %}
{% load url from future %}


{% block title %}{% block header %}
Are you sure you want to delete this incorrect personal information?
{% endblock %}{% endblock %}


{% block content %}

<ul>
	<li>
		Problem: {{ object.problem }}
	</li>
	<li>
		Explanation: {{ object.explanation }}
	</li>
</ul>

<form method="POST">
	{% csrf_token %}
	<button type="submit" class="btn btn-danger">
		<i class="icon-trash"></i> Yes, Delete It!
	</button>
	<a href="{% url "case-detail" object.case.pk %}" class="btn">
		Cancel
	</a>
</form>

{% endblock %}

templates/case/demographic_form.html
{% extends "base.html" %}
{% load url from future %}
{% load bootstrap %}

{% block title %}{% block header %}
Incorrect Personal Information
{% endblock %}{% endblock %}


{% block content %}

<form method="post" class="form-horizontal" enctype="multipart/form-data">
	{% csrf_token %}
	{{ form|bootstrap }}
	<input type="submit" class="btn btn-primary" value="Save" />
	{% if object %}
	<a href="{% url "case-detail" object.case.pk %}" class="btn">Cancel</a>
	<a href="{% url "demographic-delete" object.pk %}" class="btn btn-danger pull-right">
		<i class="icon-trash"></i> Delete
	</a>
	{% else %}
	<a href="javascript:history.go(-1)" class="btn">Cancel</a>
	{% endif %}
</form>

{% endblock %}

templates/case/inquiry_confirm_delete.html
{% extends "base.html" %}
{% load url from future %}


{% block title %}{% block header %}
Are you sure you want to delete this cased credit inquiry?
{% endblock %}{% endblock %}


{% block content %}

<ul>
	<li>
		Creditor Name: {{ object.creditor }}
	</li>
	<li>
		Account Number: {{ object.account_number }}
	</li>
	<li>
		Reason: {{ object.get_reason_display }}
	</li>
	<li>
		Explanation: {{ object.explanation }}
	</li>
</ul>

<form method="POST">
	{% csrf_token %}
	<button type="submit" class="btn btn-danger">
		<i class="icon-trash"></i> Yes, Delete It!
	</button>
	<a href="{% url "case-detail" object.case.pk %}" class="btn">
		Cancel
	</a>
</form>

{% endblock %}

templates/case/inquiry_form.html
{% extends "base.html" %}
{% load url from future %}
{% load bootstrap %}

{% block extracss %} 
<link href="{{ STATIC_URL }}/css/datepicker.css" rel="stylesheet">
{% endblock %}


{% block extrascript %} 
<script src="{{ STATIC_URL }}/js/bootstrap-datepicker.js"></script>
<script>
	$(function(){
		$('#id_date').datepicker({
			format: 'yyyy-mm-dd'
		});
	})
</script>
{% endblock %}


{% block title %}{% block header %}
Disputed Credit Iniquiry
{% endblock %}{% endblock %}


{% block content %}

<form method="post" class="form-horizontal" enctype="multipart/form-data">
	{% csrf_token %}
	{{ form|bootstrap }}
	<input type="submit" class="btn btn-primary" value="Save" />
	{% if object %}
	<a href="{% url "case-detail" object.case.pk %}" class="btn">Cancel</a>
	<a href="{% url "inquiry-delete" object.pk %}" class="btn btn-danger pull-right">
		<i class="icon-trash"></i> Delete
	</a>
	{% else %}
	<a href="javascript:history.go(-1)" class="btn">Cancel</a>
	{% endif %}
</form>

{% endblock %}